language: node_js
node_js:
  - "node"
before_install:
  - npm install -g now
install:
  - npm install
script:
  - prepush
deploy:
  on: feat/add-ci-deploy
  provider: script
  skip_cleanup: true
  script:
    - deploy
