language: node_js
node_js:
  - "node"
before_install:
  - npm install -g now
install:
  - npm install
script:
  - npm run lint
deploy:
  on: feat/add-ci-deploy
  provider: script
  skip_cleanup: true
  script:
    - npm run build && now build -p -t $NOW_TOKEN && now alias -t $NOW_TOKEN
