language: node_js
node_js:
  - "node"
install:
  - npm install
before_script:
  - npm install -g now
script:
  - npm run lint
after-success:
  - npm i -g now && now -t=$NOW_TOKEN --npm && now -t=$NOW_TOKEN alias
