language: node_js
node_js:
  - "node"
install:
  - npm install
before_script:
  - npm install -g now
script:
  - npm run lint && npm run build && now build -p -t $NOW_TOKEN && now alias -t $NOW_TOKEN
